version: 2

sources:
  - name: public
    database: cartflow
    schema: public
    tables:
      - name: orders
      - name: order_products_prior
      - name: order_products_train
      - name: products
      - name: aisles
      - name: departments

models:
  - name: stg_orders
    description: Staging model for orders table with standardized column names.
    columns:
      - name: order_id
        description: Unique identifier for each order.

      - name: user_id
        description: Unique identifier for each user.

      - name: eval_set
        description: Indicates whether the order is part of 'prior', 'train', or 'test' set.

      - name: order_number
        description: The sequence number of the order placed by the user.

      - name: order_day_of_week
        description: Day of the week the order was placed. 0 = Sunday.

      - name: order_hour_of_day
        description: Hour of the day the order was placed (0-23).

      - name: order_date
        description: The actual date the order was placed.

  - name: stg_products
    description: Products with cleaned product names
    columns:
      - name: product_id
      - name: product_name
      - name: aisle_id
      - name: department_id
      - name: product_name_clean

  - name: stg_aisles
    description: Cleaned aisles data
    columns:
      - name: aisle_id
      - name: aisle_name
      - name: aisle_name_clean

  - name: stg_departments
    description: Cleaned departments data
    columns:
      - name: department_id
      - name: department_name
      - name: department_name_clean

  - name: stg_order_products_prior
    description: Prior order product mapping with cleaned flags
    columns:
      - name: order_id
      - name: product_id
      - name: add_to_cart_order
      - name: reordered

  - name: stg_order_products_train
    description: Train order product mapping with cleaned flags
    columns:
      - name: order_id
      - name: product_id
      - name: add_to_cart_order
      - name: reordered